### ISSUE TITLE
Make ClientControl backwards compatible

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-clientControl-plugin#9]
Current plugin's build only works with 4.3.0 version of Openfire. Additional modification is needed so new versions would still work with 4.2.3.

**Comment by guusdk** [comment]
I tried to add the source file as suggested by @GregDThomas in https://github.com/igniterealtime/openfire-dbaccess-plugin/issues/2#issuecomment-457510577 but that didn't give me a plugin for which the admin pages worked with Openfire 4.2.3. Unsure how to proceed.

**Comment by GregDThomas** [comment]
Having a look now ...

**Comment by GregDThomas** [comment]
It seems the JSP page is throwing an exception; tracking that down is hard, as the code that handles the exception is itself throwing an exception due to the "old" JSP servlet classes being used. If the first exception could be overcome, the second wouldn't really be a problem.

**Comment by GregDThomas** [comment]
OK, tracked this one down. The JSP has a call to `<fmt:message key="client.features.title"/>` - looking at the generated code for that tag, when that has finished outputting the message, it makes a call to `org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(...)` - which doesn't exist on older versions of Jetty, I got away with it on Hazelcast, XML Debugger plugins due to lack of i18n support.

Notes to self; I can see three options;
a) Drop backward compatible support for plugins that use i18n.
b) Drop i18n support for plugins that we want to be backward compatible. 
c) It may be able to coerce the plugin to use an older JSP compiler that is 4.2+ compatible, possibly at the expense of losing Java 8 support in JSP pages.

**Comment by GregDThomas** [comment]
OK, I believe the PR at https://github.com/igniterealtime/openfire-clientControl-plugin/pull/12 fixes this. It downgrades the JSP compiler to the one used in Openfire 4.2 - this is forward compatible with 4.3, whereas the JSP compiler in that comes with Openfire 4.3 is not always backward compatible with Openfire 4.2.

**Comment by GregDThomas** [comment]
(NB. I also removed web-custom.xml and placed the contents in web.xml - there's no need/benefit to having them both!)
